# Generated by Django 4.2.10 on 2024-03-15 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_no', models.SmallIntegerField(unique=True)),
                ('capacity', models.SmallIntegerField()),
                ('description', models.CharField(max_length=256)),
                ('available_time', models.CharField(blank=True, choices=[('8:00-10:00', '8:00-10:00'), ('10:00-12:00', '10:00-12:00'), ('12:00-14:00', '12:00-14:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00')], max_length=256, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room/')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserve_date', models.DateField(blank=True, null=True)),
                ('available_time', models.CharField(blank=True, max_length=256, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_date',),
                'unique_together': {('room', 'reserve_date', 'available_time')},
            },
        ),
    ]
