# Generated by Django 4.2.10 on 2024-03-04 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_no', models.SmallIntegerField()),
                ('capacity', models.SmallIntegerField()),
                ('description', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='room/')),
            ],
        ),
    ]
