# Generated by Django 4.2.10 on 2024-03-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0003_reservation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="available_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("8:00-10:00", "8:00-10:00"),
                    ("10:00-12:00", "10:00-12:00"),
                    ("12:00-14:00", "12:00-14:00"),
                    ("14:00-16:00", "14:00-16:00"),
                    ("16:00-18:00", "16:00-18:00"),
                ],
                max_length=256,
                null=True,
            ),
        ),
    ]
