# Generated by Django 4.2.10 on 2024-03-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_available_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='available_time',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserve_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
