# Generated by Django 4.2.10 on 2024-03-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('room', 'reserve_date', 'available_time')},
        ),
    ]
