# Generated by Django 4.2.10 on 2024-03-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_reservation_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-created_date',)},
        ),
    ]
