# Generated by Django 4.2.10 on 2024-03-06 18:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('parent', models.CharField(blank=True, null=True)),
                ('reserve_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.reservation')),
            ],
        ),
    ]
